### ISSUE TITLE
话说现在还维护吗？

### ISSUE THREAD

**Issue by jingquanliang** [charlieethan/Trojan-Qt5#1]
这款软件还维护吗？还有就是这款软件是不是完全开源的呀，我听别人说有一部分是闭源的

**Comment by charlieethan** [comment]
> 
> 
> 这款软件还维护吗？还有就是这款软件是不是完全开源的呀，我听别人说有一部分是闭源的

原作者被请喝茶了，应该不会有维护了
开源部分占了99.9%，只有一个dll文件是闭源的

**Comment by charlieethan** [comment]
> 
> 
> > > 这款软件还维护吗？还有就是这款软件是不是完全开源的呀，我听别人说有一部分是闭源的
> > 
> > 
> > 原作者被请喝茶了，应该不会有维护了
> > 开源部分占了99.9%，只有一个dll文件是闭源的
> 
> 我刚才看来一下这个代码的proxy文件夹，好像应用的Trojan-Qt5-Core.h这个文件没有，估计包含在dll中了，这个dll文件是干嘛用的？了解吗？如果是比较核心的东西，那么其他人也维护不了这个项目了，只能等作者更新了

听说是调用Core用的，上次聊天时（3个月前）Coel 哥哥无意中说到了这个，如果要维护要么找他去要代码，要么这一部分重写。不过 QT6 都快要出来了，要改的话工程量会很大

**Comment by jingquanliang** [comment]
麻烦问一下，知道作者的联系方式吗？

**Comment by charlieethan** [comment]
> 麻烦问一下，知道作者的联系方式吗？

很抱歉我没有他的联系方式，他可能也不想再介入这件事了，毕竟人在大陆，谁知道问他要代码的是程序员还是网警？
